SELECT a.ANIMAL_ID, a.ANIMAL_TYPE, a.NAME
FROM ANIMAL_INS a
    JOIN ANIMAL_OUTS b
    ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE (a.SEX_UPON_INTAKE LIKE 'Intact Male' AND b.SEX_UPON_OUTCOME LIKE 'Neutered Male')
OR (a.SEX_UPON_INTAKE LIKE 'Intact Female' AND b.SEX_UPON_OUTCOME LIKE 'Spayed Female')