SELECT YEAR(b.SALES_DATE) as YEAR, MONTH(b.SALES_DATE) as MONTH, a.GENDER as GENDER
, count(distinct a.USER_ID) AS USERS
FROM USER_INFO a
    JOIN ONLINE_SALE b
    ON a.USER_ID = b.USER_ID
WHERE a.GENDER IS NOT NULL
GROUP BY YEAR(b.SALES_DATE), MONTH(b.SALES_DATE), a.GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC