SELECT SUM(g.SCORE) AS SCORE, e.EMP_NO AS EMP_NO, e.EMP_NAME AS EMP_NAME, e.POSITION AS POSITION, e.EMAIL AS EMAIL
FROM HR_DEPARTMENT d, HR_EMPLOYEES e, HR_GRADE g
WHERE d.DEPT_ID = e.DEPT_ID AND e.EMP_NO = g.EMP_NO AND g.YEAR = 2022
GROUP BY e.EMP_NO
ORDER BY SCORE DESC limit 1