SELECT b.USER_ID AS USER_ID, b.NICKNAME AS NICKNAME,
CONCAT(b.CITY, CONCAT(" ", CONCAT(b.STREET_ADDRESS1, CONCAT(" ", b.STREET_ADDRESS2)))) AS "전체주소",
CONCAT(SUBSTRING(b.TLNO,1,3),CONCAT("-",CONCAT(SUBSTRING(b.TLNO,4,4), CONCAT("-", SUBSTRING(b.TLNO,8,4))))) AS "전화번호"
FROM USED_GOODS_BOARD a, USED_GOODS_USER b
WHERE a.WRITER_ID = b.USER_ID
GROUP BY a.WRITER_ID
HAVING count(a.WRITER_ID) >= 3
ORDER BY USER_ID DESC