# SELECT *
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, if(STATUS = "DONE", "거래완료",if(STATUS = "RESERVED","예약중","판매중")) AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = DATE('2022-10-05')
ORDER BY BOARD_ID DESC