SELECT b.USER_ID, b.NICKNAME, sum(a.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD a
    JOIN USED_GOODS_USER b
    ON a.WRITER_ID = b.USER_ID
WHERE a.STATUS LIKE "DONE"
GROUP BY b.USER_ID
HAVING sum(a.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC


# SELECT b.USER_ID, b.NICKNAME, a.PRICE
# FROM USED_GOODS_BOARD a
#     JOIN USED_GOODS_USER b
#     ON a.WRITER_ID = b.USER_ID
# WHERE a.STATUS LIKE "DONE"